apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://query-gateway:8080/prometheus
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Prometheus
      prometheusVersion: 3.15.0
      timeInterval: 30s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://query-gateway:8080/loki
    editable: false
    jsonData:
      derivedFields: []
      maxLines: 500
