// <auto-generated />
using System;
using FamilyJobsBoard.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamilyJobsBoard.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921130747_AddGoodBehaviours")]
    partial class AddGoodBehaviours
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamilyJobsBoard.Domain.Administration.HouseholdDataReset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DeletedJobCount")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_job_count");

                    b.Property<int>("DeletedPointsEntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_points_entry_count");

                    b.Property<int>("DeletedRecurringSeriesCount")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_recurring_series_count");

                    b.Property<int>("DeletedReviewDecisionCount")
                        .HasColumnType("integer")
                        .HasColumnName("deleted_review_decision_count");

                    b.Property<Guid>("InitiatedByAdultId")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by_adult_id");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedByAdultId");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("household_data_resets", (string)null);
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.GoodBehaviours.GoodBehaviour", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTimeOffset>("LoggedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("logged_at_utc");

                    b.Property<Guid>("LoggedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("logged_by_member_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("TypeDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("type_description");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("type_id");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type_name");

                    b.HasKey("Id");

                    b.HasIndex("LoggedByMemberId");

                    b.HasIndex("RequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_good_behaviours_request_id");

                    b.HasIndex("TypeId");

                    b.HasIndex("ChildId", "LoggedAtUtc");

                    b.ToTable("good_behaviours", null, t =>
                        {
                            t.HasCheckConstraint("ck_good_behaviours_points", "points >= 0");
                        });
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.GoodBehaviours.GoodBehaviourType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_member_id");

                    b.Property<DateTimeOffset?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at_utc");

                    b.Property<Guid?>("DeactivatedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("deactivated_by_member_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid?>("UpdatedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_member_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByMemberId");

                    b.HasIndex("DeactivatedByMemberId");

                    b.HasIndex("UpdatedByMemberId");

                    b.ToTable("good_behaviour_types", null, t =>
                        {
                            t.HasCheckConstraint("ck_good_behaviour_types_points", "points >= 0");
                        });
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Households.HouseholdMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeactivatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at_utc");

                    b.Property<Guid?>("DeactivatedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("deactivated_by_member_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Nickname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nickname");

                    b.Property<DateTimeOffset?>("ProfileUpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_updated_at_utc");

                    b.Property<Guid?>("ProfileUpdatedByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_updated_by_member_id");

                    b.Property<DateTimeOffset?>("RestoredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("restored_at_utc");

                    b.Property<Guid?>("RestoredByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("restored_by_member_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id");

                    b.HasIndex("DeactivatedByMemberId");

                    b.HasIndex("ProfileUpdatedByMemberId");

                    b.HasIndex("RestoredByMemberId");

                    b.ToTable("household_members", null, t =>
                        {
                            t.HasCheckConstraint("ck_household_members_role", "role IN ('Adult', 'Child')");
                        });
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Identity.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("LastActivityAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_at_utc");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<int>("RotationVersion")
                        .HasColumnType("integer")
                        .HasColumnName("rotation_version");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Identity.HouseholdBootstrap", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<Guid?>("FirstAdultId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_adult_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.HasKey("Id");

                    b.HasIndex("FirstAdultId");

                    b.ToTable("household_bootstrap", null, t =>
                        {
                            t.HasCheckConstraint("ck_household_bootstrap_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Identity.MemberCredential", b =>
                {
                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<int>("FailedAttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_attempt_count");

                    b.Property<DateTimeOffset?>("FailedWindowStartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_window_started_at_utc");

                    b.Property<DateTimeOffset?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_utc");

                    b.Property<string>("PinHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("pin_hash");

                    b.Property<DateTimeOffset?>("PinResetAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pin_reset_at_utc");

                    b.Property<Guid?>("PinResetByMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("pin_reset_by_member_id");

                    b.Property<DateTimeOffset?>("PinSetAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pin_set_at_utc");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("state");

                    b.HasKey("MemberId");

                    b.ToTable("member_credentials", null, t =>
                        {
                            t.HasCheckConstraint("ck_member_credentials_ready_hash", "(state = 'Ready' AND pin_hash IS NOT NULL) OR (state = 'NotSet' AND pin_hash IS NULL)");
                        });
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Identity.PinSetupToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorizingAdultId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorizing_adult_id");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at_utc");

                    b.Property<Guid>("TargetMemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_member_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizingAdultId");

                    b.HasIndex("TargetMemberId");

                    b.ToTable("pin_setup_tokens", (string)null);
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Jobs.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgendaPeriod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("agenda_period");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at_utc");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<string>("RecurrenceFrequency")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("recurrence_frequency");

                    b.Property<Guid?>("RecurringJobSeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurring_job_series_id");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<TimeOnly?>("ScheduledTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ChildId", "ScheduledDate");

                    b.HasIndex("RecurringJobSeriesId", "ScheduledDate")
                        .IsUnique()
                        .HasDatabaseName("ux_jobs_recurring_series_date")
                        .HasFilter("recurring_job_series_id IS NOT NULL");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Jobs.JobReviewDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "DecidedAtUtc");

                    b.ToTable("job_review_decisions", (string)null);
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Jobs.RecurringJobSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgendaPeriod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("agenda_period");

                    b.Property<Guid>("AssignmentRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignment_request_id");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<Guid>("CreatedByAdultId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_adult_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("frequency");

                    b.Property<DateOnly>("GeneratedThrough")
                        .HasColumnType("date")
                        .HasColumnName("generated_through");

                    b.Property<int?>("MonthlyDay")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_day");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<TimeOnly?>("ScheduledTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("WeekdayMask")
                        .HasColumnType("integer")
                        .HasColumnName("weekday_mask");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdultId");

                    b.HasIndex("AssignmentRequestId", "ChildId")
                        .IsUnique()
                        .HasDatabaseName("ux_recurring_job_series_assignment_request_child");

                    b.HasIndex("ChildId", "StartDate");

                    b.ToTable("recurring_job_series", null, t =>
                        {
                            t.HasCheckConstraint("ck_recurring_job_series_schedule", "(frequency = 'Daily' AND weekday_mask = 0 AND monthly_day IS NULL) OR (frequency = 'Weekly' AND weekday_mask BETWEEN 1 AND 127 AND monthly_day IS NULL) OR (frequency = 'Monthly' AND weekday_mask = 0 AND monthly_day BETWEEN 1 AND 31)");
                        });
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Points.PointsLedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("AwardedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("awarded_at_utc");

                    b.Property<Guid>("ChildId")
                        .HasColumnType("uuid")
                        .HasColumnName("child_id");

                    b.Property<Guid?>("GoodBehaviourId")
                        .HasColumnType("uuid")
                        .HasColumnName("good_behaviour_id");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("GoodBehaviourId")
                        .IsUnique()
                        .HasDatabaseName("ux_points_ledger_entries_good_behaviour_id");

                    b.HasIndex("JobId")
                        .IsUnique()
                        .HasDatabaseName("ux_points_ledger_entries_job_id");

                    b.ToTable("points_ledger_entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_points_ledger_entries_single_source", "num_nonnulls(job_id, good_behaviour_id) = 1");
                        });
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Administration.HouseholdDataReset", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByAdultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.GoodBehaviours.GoodBehaviour", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("LoggedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyJobsBoard.Domain.GoodBehaviours.GoodBehaviourType", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.GoodBehaviours.GoodBehaviourType", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("CreatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("DeactivatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("UpdatedByMemberId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Households.HouseholdMember", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("DeactivatedByMemberId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("ProfileUpdatedByMemberId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("RestoredByMemberId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Identity.AuthSession", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Identity.HouseholdBootstrap", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("FirstAdultId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Identity.MemberCredential", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithOne()
                        .HasForeignKey("FamilyJobsBoard.Domain.Identity.MemberCredential", "MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Identity.PinSetupToken", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("AuthorizingAdultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("TargetMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Jobs.Job", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyJobsBoard.Domain.Jobs.RecurringJobSeries", null)
                        .WithMany()
                        .HasForeignKey("RecurringJobSeriesId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Jobs.JobReviewDecision", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Jobs.RecurringJobSeries", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("CreatedByAdultId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FamilyJobsBoard.Domain.Points.PointsLedgerEntry", b =>
                {
                    b.HasOne("FamilyJobsBoard.Domain.Households.HouseholdMember", null)
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyJobsBoard.Domain.GoodBehaviours.GoodBehaviour", null)
                        .WithMany()
                        .HasForeignKey("GoodBehaviourId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FamilyJobsBoard.Domain.Jobs.Job", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
