/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the selected demo family member's board.
         * @description Defaults to Fredster and returns a role-appropriate view for the selected household member.
         */
        get: operations["GetToday"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark an open job complete and pending approval.
         * @description Returns 409 when the job has already been completed.
         */
        post: operations["CompleteJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/today/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a new job for a child.
         * @description Adds a new job to the selected child's board for today.
         */
        post: operations["AddJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recurring-jobs/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a daily recurring job for a child.
         * @description Creates an adult-owned daily series and materializes duplicate-safe occurrences through an eight-week horizon.
         */
        post: operations["CreateDailyRecurringJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recurring-jobs/weekly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a weekly recurring job for a child.
         * @description Creates an adult-owned weekly series for selected weekdays and materializes duplicate-safe occurrences through an eight-week horizon.
         */
        post: operations["CreateWeeklyRecurringJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a pending job and award its points.
         * @description Returns 409 unless the job is pending approval or its points were already awarded.
         */
        post: operations["ApproveJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a pending job and return it for another try.
         * @description Records optional feedback and returns 409 unless the job is pending approval.
         */
        post: operations["RejectJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddJobRequest: {
            /** Format: uuid */
            childId: string;
            name: null | string;
            description: null | string;
            /** Format: int32 */
            points: number | string;
        };
        CreateDailyRecurringJobRequest: {
            /** Format: uuid */
            requestId: string;
            /** Format: uuid */
            viewerId: string;
            /** Format: uuid */
            childId: string;
            name: null | string;
            description: null | string;
            /** Format: int32 */
            points: number | string;
            agendaPeriod: null | string;
            /** Format: time */
            scheduledTime: null | string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: null | string;
        };
        CreateWeeklyRecurringJobRequest: {
            /** Format: uuid */
            requestId: string;
            /** Format: uuid */
            viewerId: string;
            /** Format: uuid */
            childId: string;
            name: null | string;
            description: null | string;
            /** Format: int32 */
            points: number | string;
            agendaPeriod: null | string;
            /** Format: time */
            scheduledTime: null | string;
            /** Format: date */
            startDate: string;
            /** Format: date */
            endDate: null | string;
            weekdays: null | string[];
        };
        HttpValidationProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
            errors?: {
                [key: string]: string[];
            };
        };
        JobApprovalResponse: {
            job: components["schemas"]["JobResponse"];
            /** Format: int32 */
            pointsBalance: number | string;
        };
        JobRejectionResponse: {
            /** Format: uuid */
            decisionId: string;
            reason: null | string;
            /** Format: date-time */
            rejectedAtUtc: string;
        };
        JobResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            childId: string;
            childDisplayName: string;
            name: string;
            description: string;
            /** Format: int32 */
            points: number | string;
            /** Format: date */
            scheduledDate: string;
            agendaPeriod: string;
            /** Format: time */
            scheduledTime: null | string;
            /** Format: uuid */
            recurringJobSeriesId: null | string;
            recurrenceFrequency: null | string;
            status: string;
            /** Format: date-time */
            completedAtUtc: null | string;
            /** Format: date-time */
            approvedAtUtc: null | string;
            latestRejection: null | components["schemas"]["JobRejectionResponse"];
        };
        MemberResponse: {
            /** Format: uuid */
            id: string;
            firstName: string;
            nickname: null | string;
            displayName: string;
            isAdult: boolean;
        };
        PointEarningResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            jobId: string;
            jobName: string;
            /** Format: int32 */
            points: number | string;
            /** Format: date-time */
            awardedAtUtc: string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RecurringJobResponse: {
            /** Format: uuid */
            seriesId: string;
            /** Format: date */
            generatedThrough: string;
            /** Format: int32 */
            occurrenceCount: number | string;
        };
        RejectJobRequest: {
            reason: null | string;
        };
        TodayResponse: {
            viewer: components["schemas"]["MemberResponse"];
            members: components["schemas"]["MemberResponse"][];
            /** Format: date */
            date: string;
            jobs: components["schemas"]["JobResponse"][];
            /** Format: int32 */
            pointsBalance: null | number | string;
            pointEarnings: components["schemas"]["PointEarningResponse"][];
            /** Format: int32 */
            pendingApprovalCount: number | string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetToday: {
        parameters: {
            query?: {
                memberId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TodayResponse"];
                };
            };
        };
    };
    CompleteJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    AddJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddJobRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
        };
    };
    CreateDailyRecurringJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDailyRecurringJobRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringJobResponse"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringJobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    CreateWeeklyRecurringJob: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWeeklyRecurringJobRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringJobResponse"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecurringJobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    ApproveJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobApprovalResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    RejectJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectJobRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["HttpValidationProblemDetails"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
